name: Lymox_Citybuild
version: 1.0
api-version: 1.21
main: net.lymox.citybuild.plugin.CitybuildPlugin
commands:
  setWarp:
  delWarp:
  warp:
  münzen:
  pay:
  crates:
  shop:
  item:
  settings:
  storage: